platform :ios, '13.0'

use_frameworks!

workspace 'RickAndMorty'

target 'Networking' do
    project 'Networking/Networking.project'
end


target 'Application' do
  project 'Application/Application.xcodeproj'
  
  # Pods for Application

  target 'ApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApplicationUITests' do
    # Pods for testing
  end

end
